### ISSUE TITLE
Bug in v1/gifs/search API introduced 2019-06-25 around parameter ordering?

### ISSUE THREAD

**Issue by SynVisions** [Giphy/GiphyAPI#196]
So we have code that does queries like this:

`http://api.giphy.com/v1/gifs/search?q=%s&api_key=MY_API_KEY&limit=50`

As of today we now get an empty response like this for this query, regardless of the value of `%s` (even something as common as "cat"):

```json
{
        "data": [], 
        "meta": {
          "status": 200, 
          "msg": "OK", 
          "response_id": ""
        }
      }
```

However if I shift `&limit=50` earlier so our query looks like this:

`http://api.giphy.com/v1/gifs/search?q=%s&limit=50&api_key=MY_API_KEY`

Everything is fixed and we get proper results.

My first guess was that the `&limit=50` is getting slurped up into the API key parameter but that doesn't explain why we still get HTTP 200 responses. Maybe that + something else?

Either way seems like a bug because the API docs don't seem to require the `api_key` parameter be specified last.

**Comment by khatkar** [comment]
We do not require `api_key` param at a specific position. I ran the query you reported using a valid api key and placing limit param at the end, it worked. In order to produce this issue reliably, we need the key you're using. Github isn't the right spot to put your key, so would you mind sharing your email and we can contact you? Or you can post your app name here and we can lookup the key. Your app name can be found on the developer dashboard https://developers.giphy.com/dashboard/

**Comment by SynVisions** [comment]
It's no longer happening. Seems like it was fixed.
