### ISSUE TITLE
UserWarning: You are using the giphy public api key.

### ISSUE THREAD

**Issue by Mastermind-sap** [Giphy/GiphyAPI#227]
```python
Warning (from warnings module):
  File ,<location of library>, line 241
    warnings.warn('You are using the giphy public api key. This '
UserWarning: You are using the giphy public api key. This should be used for testing only and may be deactivated in the future. See https://github.com/Giphy/GiphyAPI.
```
I am running into such kind of errors and not getting the output sometimes. Please help me solve this problem.

**Comment by JDeepD** [comment]
The message  says that the API has been granted a `public` key for small scale testing purposes. If you need a private key for medium scale purposes you need to make an [app here](https://developers.giphy.com/docs/api#quick-start-guide)

**Comment by shwetaatgiphy** [comment]
Hi @Mastermind-sap 
You're seeing this error because your app might be using the sample API key we sometimes bundle with libraries/ code samples on public platforms.
Please create your API key [here](https://developers.giphy.com/dashboard/) & apply for production access to use our API without rate limits. 

If you still run into the rate limiting, feel free to reopen this Github issue with more details. 

Hope this helps.
