### ISSUE TITLE
API has returned me an invalid GIF

### ISSUE THREAD

**Issue by VictorioMolina** [Giphy/GiphyAPI#231]
Hey! I am developing an app that uses the GIPHY API.
It is my first time using it, but I have followed the API docs correctly step by step.
The thing is that it has always returned me correct objects, but today, **the trending gifs endpoint**, has returned this response:

```
Array [
  Object {
    "height": 91,
    "id": "26gs88Xotc14xPNx6",
    "uri": "https://media4.giphy.com/media/26gs88Xotc14xPNx6/giphy-preview.gif?cid=X&rid=giphy-preview.gif",
    "width": 137,
  },
  Object {
    "height": NaN,
    "id": "XFp0fHMW5iJ54lF69n",
    "uri": undefined,
    "width": NaN,
  },
  Object {
    "height": 62,
    "id": "lpJCHVtdFdTCGrCGwE",
    "uri": "https://media0.giphy.com/media/lpJCHVtdFdTCGrCGwE/giphy-preview.gif?cid=X&rid=giphy-preview.gif",
    "width": 91,
  },   ...
```

As you can see, the GIF with id **XFp0fHMW5iJ54lF69n** is not correct, something which causes an unexpected behaviour in my app, as my component which renders gifs requires those 4 fields to be defined.

Is this a common error? Why has this happened? Should I consider to filter out the items from the response which have undefined uris or dimensions? 

Pd: I previously parsed the response to my requirements.

**Comment by shwetaatgiphy** [comment]
Hey @VictorioMolina 

Due to a number of factors a GIF might, on rare occasions, not have values for all the renditions indicated in data.images. 
To cover this edge case, our suggestion is to choose a list of renditions that serve your use case the best and navigate through those to find one that has a value. In an absolute rare case, where none of your chosen renditions have a value feel free to exclude that GIF. 

Hope this helps
