### ISSUE TITLE
No tags in random endpoint

### ISSUE THREAD

**Issue by Kuratkoo** [Giphy/GiphyAPI#34]
Hi, 

I have no tags in random endpoints. They were there 3 days ago. Could you return them back, please?

http://api.giphy.com/v1/gifs/random?tag=&api_key=dc6zaTOxFJmzC

Radim.

**Comment by dfinkler** [comment]
Hi Kuratoo,
We removed the tag data from the public key requests because we found some users were abusing the endpoint by making too many requests.  If you want a key which has tag access please apply for one and make the necessary submissions for your app.  Instructions can be found in our documentation here on Github: https://github.com/Giphy/GiphyAPI

Thanks!
