### ISSUE TITLE
rating parameter doesn't work on random queries

### ISSUE THREAD

**Issue by Alaxe** [Giphy/GiphyAPI#72]
Even though I've added a `rating=g` to my random query, I still get **PG-13** and even **R** rated GIFs

Request query:
`http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&rating=g`

To reproduce the issue get the GIF by id (just CTRL+F `"id":` in the response of the previous query) and then check the rating (CTRL+F `"rating":`). Since it's a random query you may get a few  **G** or **Y** rated images by luck, but eventually you'll get an image with a wrong rating. 

I'm using the beta API key.

**Comment by namslam** [comment]
Hi @Alaxe,

Thanks for the heads up! I was able to reproduce and will report it to our team to address and fix. Will keep you posted!

**Comment by timfrietas** [comment]
Hi @Alaxe, this should be patched up and working correctly now.  Thanks for letting us know.

**Comment by codebyjames** [comment]
I am experiencing the same issue. It doesn’t matter if I use g, of, or p-13 I still get rated r and pornographic gifs. This is a serious issue since I was using Giphy urls for my gifs in an app. It recently got suspended because of sexual content appearing where it shouldn’t have. It is really terrible that I cannot trust Giphy for rating the gifs. If you cannot rate the gifs properly, then disclose that information, or do not offer developers the options to pick a rating. I hope other developers see this and know not to trust the ratings parameters. You have to verify each url.

**Comment by jmihalsky** [comment]
If it was fixed, it is broken again. It's like the API ignores the rating parameter.

**Comment by macdhollister** [comment]
The rating seems to be a MAXIMUM rating. I just did a bit of testing and filtering by "g" gives only "g" rated gifs, filtering by "pg" gives both "pg" and "g", etc.

Is there any way to filter for a specific rating rather than a maximum rating?

**Comment by VictorioBerra** [comment]
I actually get undefined for all random gifs fetched.
