### ISSUE TITLE
Gif uploaded with the api using public key don't appear in search results

### ISSUE THREAD

**Issue by mdkass** [Giphy/GiphyAPI#73]
Hi,
I successfully uploaded gif files using giphy api with the public key and I can find the uploaded gifs y using their Id, but when doing a search for the tag used in the upload function it returns Zero results, although the tags can be found when opening the uploaded gif by their Id!
Is that because I'm using  a public key? 
take for example this uploaded gif:
http://giphy.com/gifs/mdkass-l0K4egmnKBUxx3Twc
you can see it has "mdkass" tag but mdkass search returns 0 result

**Comment by namslam** [comment]
Hi @mdkass,

Thanks for using the GIPHY API and getting in touch! The Upload BETA key allows you to upload anonymously through the API, the same way a user can upload a GIF on giphy.com if they're not logged in. This is for testing purposes only. 

Once you apply for a production key, we request a username for you to upload / host your content to. If the user falls underneath an official GIPHY Partner and Artist (you can learn more here: https://giphy.com/join/apply) then we index and make your content searchable. If it doesn't, then your GIF won't be indexed and searchable.

We are working to make all these features available to all tiers of users, but until then this is the expected behavior.

Let me know if you have any other questions thanks!

**Comment by gmartella** [comment]
Hello, 

I have a branded giphy channel and am still not seeing my gifs show up when i search their tags. Is there a period of time i should wait that takes for them to appear in searches?

Thanks!

**Comment by pratiknikam** [comment]
@gmartella did you ever figure out what was wrong? I'm having similar issue.
