### ISSUE TITLE
How to get metadata from giphy url

### ISSUE THREAD

**Issue by vovkab** [Giphy/GiphyAPI#76]
Hello

If I have giphy url, how can I get metadata from this url, for example giphyId, width, height and etc in json format?

**Comment by SteveYurka** [comment]
It doesn't appear that there is an endpoint which will do this for you based on a URL, but currently you can achieve this by manually taking the giphy ID out of the URL. There is potentially issues with this in the future, but regardless, here's how it would work:

For example, heres a response:
{
    "data": [
        {
            type: "gif",
            id: "FiGiRei2ICzzG",
            slug: "funny-cat-FiGiRei2ICzzG",
            url: "http://giphy.com/gifs/funny-cat-FiGiRei2ICzzG",
etc
}

The URL is: "http://giphy.com/gifs/funny-cat-FiGiRei2ICzzG",

You will notice the ID is "FiGiRei2ICzzG", so you can grab the ID if you strip out the "last, full word, before the last - in the string" (using something like regex)

You can then use this ID to query for GIF's by ID: http://api.giphy.com/v1/gifs/FiGiRei2ICzzG

As mentioned above though, there is a chance that one day giphy could change the URL naming scheme, so that the URL is instead giphy.com/gifs/FiGiRei2ICzzG/funny-cat, or giphy.com/gifs/FiGiRei2ICzzG-funny-cat. If they ever do this your above regex will stop working.

So you can do the above for now if you require that functionality, however, it might be worthwhile if GIPHY itself introduces an endpoint which allows for a URL to be parsed through as if it was the ID, that way this endpoint can change if the URL scheme changes.

If you only need to do this on a single GIF there will not be any issues, but if you are intending to treat URL's as giphy ID's for a longer term, then you should consider the potential problems above, or request that giphy allow a URL to be parsed to search for the GIF.

**Comment by timfrietas** [comment]
Hi @vovkab,

I don’t believe we have an endpoint that does what you want (yet) which is to take an entire GIPHY url and then return the same set of data that you can using lookup by GIF id only.

The closest thing we have that takes a URL and returns some information is this:

http://giphy.com/services/oembed/?url=http://giphy.com/gifs/funny-cat-FiGiRei2ICzzG

That will return width and height but not a separate field for the ID only, although the id is contained in the URL in a more easily parseable format.  Hope this helps!
